package com.example.pos.compliance.event.model;

public enum ComplianceEventType {
    INVOICE_ISSUED,
    INVOICE_SUBMITTED,
    INVOICE_REJECTED,
    INVOICE_CANCELLED,
    RECEIPT_PRINTED,
    RECEIPT_REPRINTED,
    CREDIT_NOTE_ISSUED,
    DEBIT_NOTE_ISSUED,
    RETRY_SCHEDULED,
    DEAD_LETTER_REACHED,
    CERTIFICATE_ROTATED,
    RECONCILIATION_STARTED,
    RECONCILIATION_COMPLETED,
    TRANSMISSION_ATTEMPTED,
    TRANSMISSION_SUCCEEDED,
    TRANSMISSION_FAILED
}
