package com.example.pos.sync.event;

public enum EventType {
    SALE_CREATED,
    SALE_CANCELLED,
    SALE_SUSPENDED,
    SALE_RESUMED,
    PAYMENT_RECEIVED,
    PAYMENT_REFUNDED,
    SALE_RETURNED,
    STOCK_RECEIVED,
    STOCK_DEDUCTED,
    STOCK_ADJUSTED,
    STOCK_MOVEMENT,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    PRICE_UPDATED,
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,
    SHIFT_OPENED,
    SHIFT_CLOSED,
    BRANCH_REGISTERED,
    TERMINAL_REGISTERED
}
