package com.example.pos.inventory.stockmovements.service;

import com.example.pos.common.exception.BadRequestException;
import com.example.pos.common.exception.ResourceNotFoundException;
import com.example.pos.inventory.stockmovements.dto.StockMovementRequestDto;
import com.example.pos.inventory.stockmovements.model.StockMovements;
import com.example.pos.inventory.stockmovements.repository.StockMovementsRepository;
import com.example.pos.security.auth.AuthenticatedUserContext;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.UUID;

@Service
@Transactional
public class StockMovementsService {

    private final StockMovementsRepository movementsRepository;
    private final AuthenticatedUserContext current;

    public StockMovementsService(StockMovementsRepository movementsRepository,
                                 AuthenticatedUserContext current) {
        this.movementsRepository = movementsRepository;
        this.current = current;
    }

    public StockMovements recordMovement(StockMovementRequestDto dto) {
        throw new BadRequestException(
                "Stock movements are generated by checkout, goods receipt, returns, and approved adjustments",
                "DIRECT_STOCK_MOVEMENT_DISABLED");
    }

    @Transactional(readOnly = true)
    public Page<StockMovements> getMovementsByBatch(UUID batchId, Pageable pageable) {
        return movementsRepository.findByMedicineBatchesIdAndBranchId(
                batchId, current.branchId(), pageable);
    }

    @Transactional(readOnly = true)
    public Page<StockMovements> getMovementsByBranch(UUID branchId, Pageable pageable) {
        if (branchId != null) current.requireBranch(branchId);
        return movementsRepository.findByBranchId(current.branchId(), pageable);
    }

    @Transactional(readOnly = true)
    public Page<StockMovements> getMovementsByBranchAndDateRange(
            UUID branchId, LocalDate start, LocalDate end, Pageable pageable) {
        current.requireBranch(branchId);
        if (start == null || end == null || start.isAfter(end)) {
            throw new BadRequestException("A valid start and end date are required", "INVALID_DATE_RANGE");
        }
        return movementsRepository.findByBranchIdAndMovementDateBetween(
                current.branchId(), start, end, pageable);
    }

    @Transactional(readOnly = true)
    public StockMovements getMovementById(UUID id) {
        return movementsRepository.findByIdAndBranchId(id, current.branchId())
                .orElseThrow(() -> new ResourceNotFoundException("StockMovement", id));
    }
}
